package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcmCliente generated by hbm2java
 */
@Entity
@Table(name="bcm_cliente"
    ,catalog="bruno_monteiro"
)
public class BcmCliente  implements java.io.Serializable {


     private int bcmIdCodigo;
     private String bcmNome;
     private String bcmTelefone;
     private String bcmCpf;
     private String bcmRg;
     private String bcmOrgaoExpedidor;
     private Date bcmDataExpedicao;
     private String bcmNacionalidade;
     private Date bcmDataNascimento;
     private String bcmSexo;
     private String bcmRua;
     private String bcmBairro;
     private String bcmNumero;
     private String bcmCidade;
     private String bcmPais;

    public BcmCliente() {
    }

	
    public BcmCliente(int bcmIdCodigo) {
        this.bcmIdCodigo = bcmIdCodigo;
    }
    public BcmCliente(int bcmIdCodigo, String bcmNome, String bcmTelefone, String bcmCpf, String bcmRg, String bcmOrgaoExpedidor, Date bcmDataExpedicao, String bcmNacionalidade, Date bcmDataNascimento, String bcmSexo, String bcmRua, String bcmBairro, String bcmNumero, String bcmCidade, String bcmPais) {
       this.bcmIdCodigo = bcmIdCodigo;
       this.bcmNome = bcmNome;
       this.bcmTelefone = bcmTelefone;
       this.bcmCpf = bcmCpf;
       this.bcmRg = bcmRg;
       this.bcmOrgaoExpedidor = bcmOrgaoExpedidor;
       this.bcmDataExpedicao = bcmDataExpedicao;
       this.bcmNacionalidade = bcmNacionalidade;
       this.bcmDataNascimento = bcmDataNascimento;
       this.bcmSexo = bcmSexo;
       this.bcmRua = bcmRua;
       this.bcmBairro = bcmBairro;
       this.bcmNumero = bcmNumero;
       this.bcmCidade = bcmCidade;
       this.bcmPais = bcmPais;
    }
   
     @Id 

    
    @Column(name="bcm_id_codigo", unique=true, nullable=false)
    public int getBcmIdCodigo() {
        return this.bcmIdCodigo;
    }
    
    public void setBcmIdCodigo(int bcmIdCodigo) {
        this.bcmIdCodigo = bcmIdCodigo;
    }

    
    @Column(name="bcm_nome", length=50)
    public String getBcmNome() {
        return this.bcmNome;
    }
    
    public void setBcmNome(String bcmNome) {
        this.bcmNome = bcmNome;
    }

    
    @Column(name="bcm_telefone", length=15)
    public String getBcmTelefone() {
        return this.bcmTelefone;
    }
    
    public void setBcmTelefone(String bcmTelefone) {
        this.bcmTelefone = bcmTelefone;
    }

    
    @Column(name="bcm_cpf", length=14)
    public String getBcmCpf() {
        return this.bcmCpf;
    }
    
    public void setBcmCpf(String bcmCpf) {
        this.bcmCpf = bcmCpf;
    }

    
    @Column(name="bcm_rg", length=14)
    public String getBcmRg() {
        return this.bcmRg;
    }
    
    public void setBcmRg(String bcmRg) {
        this.bcmRg = bcmRg;
    }

    
    @Column(name="bcm_orgao_expedidor", length=30)
    public String getBcmOrgaoExpedidor() {
        return this.bcmOrgaoExpedidor;
    }
    
    public void setBcmOrgaoExpedidor(String bcmOrgaoExpedidor) {
        this.bcmOrgaoExpedidor = bcmOrgaoExpedidor;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bcm_data_expedicao", length=19)
    public Date getBcmDataExpedicao() {
        return this.bcmDataExpedicao;
    }
    
    public void setBcmDataExpedicao(Date bcmDataExpedicao) {
        this.bcmDataExpedicao = bcmDataExpedicao;
    }

    
    @Column(name="bcm_nacionalidade", length=50)
    public String getBcmNacionalidade() {
        return this.bcmNacionalidade;
    }
    
    public void setBcmNacionalidade(String bcmNacionalidade) {
        this.bcmNacionalidade = bcmNacionalidade;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bcm_data_nascimento", length=19)
    public Date getBcmDataNascimento() {
        return this.bcmDataNascimento;
    }
    
    public void setBcmDataNascimento(Date bcmDataNascimento) {
        this.bcmDataNascimento = bcmDataNascimento;
    }

    
    @Column(name="bcm_sexo", length=20)
    public String getBcmSexo() {
        return this.bcmSexo;
    }
    
    public void setBcmSexo(String bcmSexo) {
        this.bcmSexo = bcmSexo;
    }

    
    @Column(name="bcm_rua", length=100)
    public String getBcmRua() {
        return this.bcmRua;
    }
    
    public void setBcmRua(String bcmRua) {
        this.bcmRua = bcmRua;
    }

    
    @Column(name="bcm_bairro", length=50)
    public String getBcmBairro() {
        return this.bcmBairro;
    }
    
    public void setBcmBairro(String bcmBairro) {
        this.bcmBairro = bcmBairro;
    }

    
    @Column(name="bcm_numero", length=10)
    public String getBcmNumero() {
        return this.bcmNumero;
    }
    
    public void setBcmNumero(String bcmNumero) {
        this.bcmNumero = bcmNumero;
    }

    
    @Column(name="bcm_cidade", length=50)
    public String getBcmCidade() {
        return this.bcmCidade;
    }
    
    public void setBcmCidade(String bcmCidade) {
        this.bcmCidade = bcmCidade;
    }

    
    @Column(name="bcm_pais", length=50)
    public String getBcmPais() {
        return this.bcmPais;
    }
    
    public void setBcmPais(String bcmPais) {
        this.bcmPais = bcmPais;
    }


}


