package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BcmProduto generated by hbm2java
 */
@Entity
@Table(name="bcm_produto"
    ,catalog="bruno_monteiro"
)
public class BcmProduto  implements java.io.Serializable {


     private int bcmIdCodigo;
     private String bcmNome;
     private double bcmValor;
     private String bcmCategoria;
     private String bcmMarca;
     private String bcmModelo;
     private String bcmDescricao;

    public BcmProduto() {
    }

	
    public BcmProduto(int bcmIdCodigo) {
        this.bcmIdCodigo = bcmIdCodigo;
    }
    public BcmProduto(int bcmIdCodigo, String bcmNome, double bcmValor, String bcmCategoria, String bcmMarca, String bcmModelo, String bcmDescricao) {
       this.bcmIdCodigo = bcmIdCodigo;
       this.bcmNome = bcmNome;
       this.bcmValor = bcmValor;
       this.bcmCategoria = bcmCategoria;
       this.bcmMarca = bcmMarca;
       this.bcmModelo = bcmModelo;
       this.bcmDescricao = bcmDescricao;
    }
   
     @Id 

    
    @Column(name="bcm_id_codigo", unique=true, nullable=false)
    public int getBcmIdCodigo() {
        return this.bcmIdCodigo;
    }
    
    public void setBcmIdCodigo(int bcmIdCodigo) {
        this.bcmIdCodigo = bcmIdCodigo;
    }

    
    @Column(name="bcm_nome", length=100)
    public String getBcmNome() {
        return this.bcmNome;
    }
    
    public void setBcmNome(String bcmNome) {
        this.bcmNome = bcmNome;
    }

    
    @Column(name="bcm_valor", precision=9)
    public double getBcmValor() {
        return this.bcmValor;
    }
    
    public void setBcmValor(double bcmValor) {
        this.bcmValor = bcmValor;
    }

    
    @Column(name="bcm_categoria", length=100)
    public String getBcmCategoria() {
        return this.bcmCategoria;
    }
    
    public void setBcmCategoria(String bcmCategoria) {
        this.bcmCategoria = bcmCategoria;
    }

    
    @Column(name="bcm_marca", length=100)
    public String getBcmMarca() {
        return this.bcmMarca;
    }
    
    public void setBcmMarca(String bcmMarca) {
        this.bcmMarca = bcmMarca;
    }

    
    @Column(name="bcm_modelo", length=50)
    public String getBcmModelo() {
        return this.bcmModelo;
    }
    
    public void setBcmModelo(String bcmModelo) {
        this.bcmModelo = bcmModelo;
    }

    
    @Column(name="bcm_descricao", length=200)
    public String getBcmDescricao() {
        return this.bcmDescricao;
    }
    
    public void setBcmDescricao(String bcmDescricao) {
        this.bcmDescricao = bcmDescricao;
    }
}


