package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcmUsuarios generated by hbm2java
 */
@Entity
@Table(name="bcm_usuarios"
    ,catalog="bruno_monteiro"
)
public class BcmUsuarios  implements java.io.Serializable {


     private int bcmIdUsuario;
     private String bcmNome;
     private String bcmApelido;
     private String bcmCpf;
     private Date bcmDataNascimento;
     private String bcmSenha;
     private Integer bcmNivel;
     private String bcmAtivo;

    public BcmUsuarios() {
    }

	
    public BcmUsuarios(int bcmIdUsuario) {
        this.bcmIdUsuario = bcmIdUsuario;
    }
    public BcmUsuarios(int bcmIdUsuario, String bcmNome, String bcmApelido, String bcmCpf, Date bcmDataNascimento, String bcmSenha, Integer bcmNivel, String bcmAtivo) {
       this.bcmIdUsuario = bcmIdUsuario;
       this.bcmNome = bcmNome;
       this.bcmApelido = bcmApelido;
       this.bcmCpf = bcmCpf;
       this.bcmDataNascimento = bcmDataNascimento;
       this.bcmSenha = bcmSenha;
       this.bcmNivel = bcmNivel;
       this.bcmAtivo = bcmAtivo;
    }
   
     @Id 

    
    @Column(name="bcm_id_usuario", unique=true, nullable=false)
    public int getBcmIdUsuario() {
        return this.bcmIdUsuario;
    }
    
    public void setBcmIdUsuario(int bcmIdUsuario) {
        this.bcmIdUsuario = bcmIdUsuario;
    }

    
    @Column(name="bcm_nome", length=50)
    public String getBcmNome() {
        return this.bcmNome;
    }
    
    public void setBcmNome(String bcmNome) {
        this.bcmNome = bcmNome;
    }

    
    @Column(name="bcm_apelido", length=25)
    public String getBcmApelido() {
        return this.bcmApelido;
    }
    
    public void setBcmApelido(String bcmApelido) {
        this.bcmApelido = bcmApelido;
    }

    
    @Column(name="bcm_cpf", length=14)
    public String getBcmCpf() {
        return this.bcmCpf;
    }
    
    public void setBcmCpf(String bcmCpf) {
        this.bcmCpf = bcmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="bcm_data_nascimento", length=10)
    public Date getBcmDataNascimento() {
        return this.bcmDataNascimento;
    }
    
    public void setBcmDataNascimento(Date bcmDataNascimento) {
        this.bcmDataNascimento = bcmDataNascimento;
    }

    
    @Column(name="bcm_senha", length=20)
    public String getBcmSenha() {
        return this.bcmSenha;
    }
    
    public void setBcmSenha(String bcmSenha) {
        this.bcmSenha = bcmSenha;
    }

    
    @Column(name="bcm_nivel")
    public Integer getBcmNivel() {
        return this.bcmNivel;
    }
    
    public void setBcmNivel(Integer bcmNivel) {
        this.bcmNivel = bcmNivel;
    }

    
    @Column(name="bcm_ativo", length=1)
    public String getBcmAtivo() {
        return this.bcmAtivo;
    }
    
    public void setBcmAtivo(String bcmAtivo) {
        this.bcmAtivo = bcmAtivo;
    }




}


