package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BcmVenda generated by hbm2java
 */
@Entity
@Table(name="bcm_venda"
    ,catalog="bruno_monteiro"
)
public class BcmVenda  implements java.io.Serializable {


     private int bcmIdVenda;
     private BcmCliente bcmCliente;
     private BcmFuncionarios bcmFuncionarios;
     private Date bcmData;
     private double bcmTotal;
     private double bcmDesconto;

    public BcmVenda() {
    }

	
    public BcmVenda(int bcmIdVenda, BcmCliente bcmCliente, BcmFuncionarios bcmFuncionarios) {
        this.bcmIdVenda = bcmIdVenda;
        this.bcmCliente = bcmCliente;
        this.bcmFuncionarios = bcmFuncionarios;
    }
    public BcmVenda(int bcmIdVenda, BcmCliente bcmCliente, BcmFuncionarios bcmFuncionarios, Date bcmData, double bcmTotal, double bcmDesconto) {
       this.bcmIdVenda = bcmIdVenda;
       this.bcmCliente = bcmCliente;
       this.bcmFuncionarios = bcmFuncionarios;
       this.bcmData = bcmData;
       this.bcmTotal = bcmTotal;
       this.bcmDesconto = bcmDesconto;
    }
   
     @Id 

    
    @Column(name="bcm_id_venda", unique=true, nullable=false)
    public int getBcmIdVenda() {
        return this.bcmIdVenda;
    }
    
    public void setBcmIdVenda(int bcmIdVenda) {
        this.bcmIdVenda = bcmIdVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_cliente", nullable=false)
    public BcmCliente getBcmCliente() {
        return this.bcmCliente;
    }
    
    public void setBcmCliente(BcmCliente bcmCliente) {
        this.bcmCliente = bcmCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_funcionarios", nullable=false)
    public BcmFuncionarios getBcmFuncionarios() {
        return this.bcmFuncionarios;
    }
    
    public void setBcmFuncionarios(BcmFuncionarios bcmFuncionarios) {
        this.bcmFuncionarios = bcmFuncionarios;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bcm_data", length=19)
    public Date getBcmData() {
        return this.bcmData;
    }
    
    public void setBcmData(Date bcmData) {
        this.bcmData = bcmData;
    }

    
    @Column(name="bcm_total", precision=9)
    public double getBcmTotal() {
        return this.bcmTotal;
    }
    
    public void setBcmTotal(double bcmTotal) {
        this.bcmTotal = bcmTotal;
    }

    
    @Column(name="bcm_desconto", precision=9)
    public double getBcmDesconto() {
        return this.bcmDesconto;
    }
    
    public void setBcmDesconto(double bcmDesconto) {
        this.bcmDesconto = bcmDesconto;
    }

}


