package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BcmVendaProduto generated by hbm2java
 */
@Entity
@Table(name="bcm_venda_produto"
    ,catalog="db_bruno_monteiro"
)
public class BcmVendaProduto  implements java.io.Serializable {


     private int bcmIdCodigo;
     private BcmProduto bcmProduto;
     private BcmVenda bcmVenda;
     private double bcmSubtotal;
     private int bcmQuantidade;

    public BcmVendaProduto() {
    }

	
    public BcmVendaProduto(BcmProduto bcmProduto, BcmVenda bcmVenda) {
        this.bcmProduto = bcmProduto;
        this.bcmVenda = bcmVenda;
    }
    public BcmVendaProduto(BcmProduto bcmProduto, BcmVenda bcmVenda, double bcmSubtotal, int bcmQuantidade) {
       this.bcmProduto = bcmProduto;
       this.bcmVenda = bcmVenda;
       this.bcmSubtotal = bcmSubtotal;
       this.bcmQuantidade = bcmQuantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="bcm_id_codigo", unique=true, nullable=false)
    public int getBcmIdCodigo() {
        return this.bcmIdCodigo;
    }
    
    public void setBcmIdCodigo(int bcmIdCodigo) {
        this.bcmIdCodigo = bcmIdCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_produto", nullable=false)
    public BcmProduto getBcmProduto() {
        return this.bcmProduto;
    }
    
    public void setBcmProduto(BcmProduto bcmProduto) {
        this.bcmProduto = bcmProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_venda", nullable=false)
    public BcmVenda getBcmVenda() {
        return this.bcmVenda;
    }
    
    public void setBcmVenda(BcmVenda bcmVenda) {
        this.bcmVenda = bcmVenda;
    }

    
    @Column(name="bcm_subtotal", precision=9)
    public double getBcmSubtotal() {
        return this.bcmSubtotal;
    }
    
    public void setBcmSubtotal(double bcmSubtotal) {
        this.bcmSubtotal = bcmSubtotal;
    }

    
    @Column(name="bcm_quantidade")
    public int getBcmQuantidade() {
        return this.bcmQuantidade;
    }
    
    public void setBcmQuantidade(int bcmQuantidade) {
        this.bcmQuantidade = bcmQuantidade;
    }

}


