package bean;
// Generated 22/09/2025 11:40:51 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BcmVendaProduto generated by hbm2java
 */
@Entity
@Table(name="bcm_venda_produto"
    ,catalog="bruno_monteiro"
)
public class BcmVendaProduto  implements java.io.Serializable {


     private Integer idCodigo;
     private BcmProduto bcmProduto;
     private BcmVenda bcmVenda;
     private BigDecimal subtotal;
     private Integer quantidade;

    public BcmVendaProduto() {
    }

	
    public BcmVendaProduto(BcmProduto bcmProduto, BcmVenda bcmVenda) {
        this.bcmProduto = bcmProduto;
        this.bcmVenda = bcmVenda;
    }
    public BcmVendaProduto(BcmProduto bcmProduto, BcmVenda bcmVenda, BigDecimal subtotal, Integer quantidade) {
       this.bcmProduto = bcmProduto;
       this.bcmVenda = bcmVenda;
       this.subtotal = subtotal;
       this.quantidade = quantidade;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_codigo", unique=true, nullable=false)
    public Integer getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(Integer idCodigo) {
        this.idCodigo = idCodigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_produto", nullable=false)
    public BcmProduto getBcmProduto() {
        return this.bcmProduto;
    }
    
    public void setBcmProduto(BcmProduto bcmProduto) {
        this.bcmProduto = bcmProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bcm_fk_venda", nullable=false)
    public BcmVenda getBcmVenda() {
        return this.bcmVenda;
    }
    
    public void setBcmVenda(BcmVenda bcmVenda) {
        this.bcmVenda = bcmVenda;
    }

    
    @Column(name="subtotal", precision=9)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }

    
    @Column(name="quantidade")
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }

}


